

const mongoose = require('mongoose');

const funkoSchema = mongoose.Schema({
    name: {
        type: String,
        required: true,
    },
    series: {
        type: String,
        enum: [
            'Pop! 8-Bit',
            'Pop! Ad Icons',
            'Pop! Air Force',
            'Pop! Albums',
            'Pop! Animation',
            'Pop! Aquasox',
            'Pop! Army',
            'Pop! Around the World',
            'Pop! Artists',
            'Pop! Art Covers',
            'Pop! Art Series',
            'Pop! Asia',
            'Pop! Bape',
            'Pop! Basketball',
            'Pop! Board Games',
            'Pop! Books',
            'Pop! Boxing',
            'Pop! Broadway',
            'Pop! Build a Bear',
            'Pop! Candy',
            'Pop! Christmas',
            'Pop! Classics',
            'Pop! College',
            'Pop! Comedians',
            'Pop! Comic Covers',
            'Pop! Comics',
            'Pop! Conan',
            'Pop! Custom',
            'Pop! Deluxe',
            'Pop! Deluxe Moments',
            'Pop! Die-Cast',
            'Pop! Digital',
            'Pop! Disney',
            'Pop! Directors',
            'Pop! Drag Queens',
            'Pop! Fantastic Beasts',
            'Pop! Fashion',
            'Pop! Foodies',
            'Pop! Football',
            'Pop! Funko (Freddy Funko)',
            'Pop! Funko (Fantastik Plastik)',
            'Pop! Funko (Lance)',
            'Pop! Game of Thrones',
            'Pop! Games',
            'Pop! Game Covers',
            'Pop! Golf',
            'Pop! GPK',
            'Pop! Halo',
            'Pop! Harry Potter',
            'Pop! Heroes',
            'Pop! Hockey',
            'Pop! Holidays',
            'Pop! House of the Dragons',
            'Pop! Icons',
            'Pop! League of Legends',
            'Pop! Magic: The Gathering',
            'Pop! Marines',
            'Pop! Marvel',
            'Pop! Magazine Covers',
            'Pop! Minis',
            'Pop! MLB',
            'Pop! Moments',
            'Pop! Monsters',
            'Pop! Movie Posters',
            'Pop! Movies',
            'Pop! Muppets',
            'Pop! Myths',
            'Pop! My Little Pony',
            'Pop! NASCAR',
            'Pop! Navy',
            'Pop! NBA Mascots',
            'Pop! NFL',
            'Pop! Pets',
            'Pop! Pusheen',
            'Pop! Racing',
            'Pop! Retro Toys',
            'Pop! Rides',
            'Pop! Rocks',
            'Pop! Royals',
            'Pop! Sanrio',
            'Pop! Sci-Fi',
            'Pop! Sesame Street',
            'Pop! SNL',
            'Pop! South Park',
            'Special Edition Pop!',
            'Pop! Sports',
            'Pop! Sports Legends',
            'Pop! Stan Lee',
            'Pop! Star Wars',
            'Pop! Television',
            'Pop! Tennis',
            'Pop! The Vote',
            'Pop! Town',
            'Pop! Town Christmas',
            'Pop! Trading Cards',
            'Pop! Trains',
            'Pop! Trolls',
            'Pop! UFC',
            'Pop! Uglydoll',
            'Pop! Valiant',
            'Pop! Vans',
            'Pop! VHS Covers',
            'Pop! Wreck-It Ralph',
            'Pop! Wrestling',
            'Pop! WWE',
            'Pop! WWE Covers',
            'Pop! Zodiac',
        ],
        required: true,
    },
    number: {
        type: Number,
        required: true,
    },
    rarity: {
        type: String,
        required: false,
    },
    // image: {
    //     required: true,
    // },
    owner: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
    }
});

const Funko = mongoose.model('Funko', funkoSchema);

module.exports = Funko;